import { useState, useEffect } from 'react';
import { Bot, BarChart2, Bell, Shield, Activity, Zap, Lock, Key, CheckCircle, Send, Sparkles } from 'lucide-react';
import MarketScanner from './components/MarketScanner';
import SignalBot from './components/SignalBot';
import MarketNews from './components/MarketNews';
import TradenRadar from './components/TradenRadar';
import PreciousMetals from './components/PreciousMetals';
import HalalGuide from './components/HalalGuide';
import InvestmentBot from './components/InvestmentBot';
import './App.css';

// Admin / Allowed User IDs or Master Activation Code
const MASTER_VIP_CODE = 'TRADEN2026';
const WHITELISTED_TELEGRAM_IDS = [1914514519, 12345678, 87654321]; // Admin Telegram ID added!

function App() {
  const [tgUser, setTgUser] = useState(null);
  const [currentView, setCurrentView] = useState('home');
  const [selectedSymbol, setSelectedSymbol] = useState('BTC/USDT');
  
  // Authorization state
  const [isAuthorized, setIsAuthorized] = useState(false);
  const [activationInput, setActivationInput] = useState('');
  const [activationError, setActivationError] = useState(false);
  const [showCodeInput, setShowCodeInput] = useState(false);

  useEffect(() => {
    // Check if user previously activated via stored token
    const storedAuth = localStorage.getItem('traden_user_authorized');
    if (storedAuth === 'true') {
      setIsAuthorized(true);
    }

    if (window.Telegram && window.Telegram.WebApp) {
      const tg = window.Telegram.WebApp;
      tg.expand();
      if (tg.initDataUnsafe && tg.initDataUnsafe.user) {
        const u = tg.initDataUnsafe.user;
        setTgUser(u);
        
        // Auto authorize if user ID is in admin whitelist (e.g. 1914514519)
        if (WHITELISTED_TELEGRAM_IDS.includes(u.id) || u.id === 1914514519) {
          setIsAuthorized(true);
          localStorage.setItem('traden_user_authorized', 'true');
        }
      }
    }
  }, []);

  const handleActivateWithCode = () => {
    const cleanInput = activationInput.trim().toUpperCase();

    // Accept master key OR any key generated by Telegram Bot starting with TRADEN-
    const isValidKey = cleanInput === MASTER_VIP_CODE || 
                       cleanInput.startsWith('TRADEN-') || 
                       cleanInput.includes('TRADEN');

    if (isValidKey) {
      setIsAuthorized(true);
      localStorage.setItem('traden_user_authorized', 'true');
      setActivationError(false);
    } else {
      setActivationError(true);
    }
  };

  // 🔒 RESTRICTED ACCESS SCREEN (If user is not authorized by Admin)
  if (!isAuthorized) {
    return (
      <div className="app-container" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '85vh', textAlign: 'center', padding: '20px' }}>
        
        <div style={{ 
          width: '80px', height: '80px', borderRadius: '50%', 
          background: 'rgba(239, 68, 68, 0.12)', border: '1px solid rgba(239, 68, 68, 0.3)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px auto',
          boxShadow: '0 0 30px rgba(239, 68, 68, 0.2)'
        }}>
          <Lock size={40} color="#f87171" />
        </div>

        <h2 style={{ fontSize: '24px', fontWeight: 'bold', color: '#fff', margin: '0 0 10px 0' }}>
          الحساب غير مفعل 🔒
        </h2>

        <p style={{ fontSize: '13px', color: '#9ca3af', lineHeight: '1.6', maxWidth: '340px', margin: '0 0 20px 0' }}>
          عذراً، استخدام منصة <b>Traden AI</b> يتطلب إذن التفعيل المباشر من إدارة البوت.
        </p>

        {tgUser && (
          <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '10px 16px', fontSize: '12px', color: '#f59e0b', marginBottom: '20px' }}>
            معرف الحساب: <b>@{tgUser.username || tgUser.first_name || tgUser.id}</b> (ID: {tgUser.id})
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', width: '100%', maxWidth: '320px' }}>
          
          {/* Telegram Contact Button */}
          <a 
            href={tgUser ? `https://t.me/share/url?url=طلب%20تفعيل%20حساب%20Traden%20AI%20للمستخدم%20ID:%20${tgUser.id}` : 'https://t.me/'}
            target="_blank" 
            rel="noreferrer"
            style={{ 
              background: '#f59e0b', color: '#000', textDecoration: 'none', 
              padding: '14px', borderRadius: '12px', fontWeight: 'bold', fontSize: '14px',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px',
              boxShadow: '0 0 15px rgba(245, 158, 11, 0.3)'
            }}
          >
            <Send size={18} />
            <span>تواصل مع الأدمن لتفعيل الحساب 📲</span>
          </a>

          {/* Enter Code Toggle Button */}
          <button 
            onClick={() => setShowCodeInput(!showCodeInput)}
            style={{ 
              background: 'rgba(255,255,255,0.04)', color: '#fff', border: '1px solid rgba(255,255,255,0.1)',
              padding: '12px', borderRadius: '12px', fontSize: '13px', cursor: 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px'
            }}
          >
            <Key size={16} color="#a855f7" />
            <span>أدخل كود تفعيل الأدمن (VIP)</span>
          </button>

          {/* Activation Code Input Box */}
          {showCodeInput && (
            <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(168, 85, 247, 0.3)', borderRadius: '14px', padding: '14px', marginTop: '6px' }}>
              <input 
                type="text"
                placeholder="أدخل رمز كود التفعيل هُنا..."
                value={activationInput}
                onChange={(e) => { setActivationInput(e.target.value); setActivationError(false); }}
                style={{
                  width: '100%', background: 'rgba(0,0,0,0.4)', border: `1px solid ${activationError ? '#f87171' : 'rgba(255,255,255,0.1)'}`,
                  borderRadius: '10px', padding: '10px', color: '#fff', fontSize: '13px', textAlign: 'center', outline: 'none', boxSizing: 'border-box'
                }}
              />
              {activationError && (
                <div style={{ color: '#f87171', fontSize: '11px', marginTop: '6px' }}>كود التفعيل غير صحيح ❌</div>
              )}
              <button 
                onClick={handleActivateWithCode}
                style={{
                  width: '100%', background: '#a855f7', color: '#fff', border: 'none',
                  borderRadius: '10px', padding: '10px', marginTop: '10px', fontWeight: 'bold', fontSize: '13px', cursor: 'pointer'
                }}
              >
                تفعيل الحساب الآن ✨
              </button>
            </div>
          )}

        </div>

      </div>
    );
  }

  // ✅ AUTHORIZED FULL APP VIEW
  if (currentView === 'investment_bot') {
    return (
      <div className="app-container">
        <InvestmentBot onBack={() => setCurrentView('home')} />
      </div>
    );
  }

  if (currentView === 'halal_guide') {
    return (
      <div className="app-container">
        <HalalGuide onBack={() => setCurrentView('home')} />
      </div>
    );
  }

  if (currentView === 'precious_metals') {
    return (
      <div className="app-container">
        <PreciousMetals onBack={() => setCurrentView('home')} />
      </div>
    );
  }

  if (currentView === 'traden_radar') {
    return (
      <div className="app-container">
        <TradenRadar 
          onBack={() => setCurrentView('home')} 
          onOpenBot={(symbol) => {
            if (symbol) setSelectedSymbol(symbol);
            setCurrentView('signal_bot');
          }}
        />
      </div>
    );
  }

  if (currentView === 'market_scanner') {
    return (
      <div className="app-container">
        <MarketScanner onBack={() => setCurrentView('home')} />
      </div>
    );
  }

  if (currentView === 'signal_bot') {
    return (
      <div className="app-container">
        <SignalBot initialSymbol={selectedSymbol} onBack={() => setCurrentView('home')} />
      </div>
    );
  }

  if (currentView === 'market_news') {
    return (
      <div className="app-container">
        <MarketNews onBack={() => setCurrentView('home')} />
      </div>
    );
  }

  return (
    <div className="app-container">
      
      <header className="header">
        <div className="header-title">
          تداول أذكى <span>مع Traden AI ✦</span>
        </div>
        <div style={{ fontSize: '12px', color: '#9ca3af' }}>
          إشارات ذكية · تحليل فني · فتح صفقات مباشر
        </div>
        
        {tgUser && (
          <div style={{ fontSize: '13px', color: '#10b981', display: 'flex', alignItems: 'center', gap: '4px', marginTop: '4px' }}>
            <CheckCircle size={14} />
            <span>حساب مفعل: {tgUser.first_name}</span>
          </div>
        )}
      </header>

      <section>
        <div className="section-title">
          <Bot size={18} />
          البوتات الذكية
        </div>
        <div className="grid-2">
          <div className="card" onClick={() => setCurrentView('signal_bot')}>
            <span className="card-icon">📡</span>
            <div className="card-title">Traden Bot (بوت التوصيات) 🤖</div>
            <div className="card-desc">توليد أهداف الصفقات (TP/SL) وإرسالها للتليجرام</div>
          </div>
          <div className="card" onClick={() => setCurrentView('investment_bot')} style={{ cursor: 'pointer' }}>
            <span className="card-icon">🌱</span>
            <div className="card-title">بوت الاستثمار الذكي ✦</div>
            <div className="card-desc">أفضل أصول للاحتفاظ والدخل السلبي (HODL & DCA)</div>
          </div>
        </div>
      </section>

      <section>
        <div className="section-title">
          <Zap size={18} />
          الأدوات والتحليل
        </div>
        <div className="grid-3">
          <div className="card" onClick={() => setCurrentView('traden_radar')} style={{ border: '1px solid rgba(245, 158, 11, 0.4)', background: 'rgba(245, 158, 11, 0.05)' }}>
            <span className="card-icon">📡</span>
            <div className="card-title">ماسح الأسواق ✦</div>
            <div className="badge" style={{ background: '#f59e0b', color: '#000' }}>رادار حي 🔥</div>
          </div>
          <div className="card" onClick={() => setCurrentView('market_scanner')}>
            <BarChart2 size={24} color="#60a5fa" />
            <div className="card-title">فاحص المؤشرات 📊</div>
          </div>
          <div className="card" onClick={() => setCurrentView('precious_metals')}>
            <span className="card-icon">🥇</span>
            <div className="card-title">المعادن الثمينة</div>
          </div>
          <div className="card" onClick={() => setCurrentView('halal_guide')}>
            <Shield size={24} color="#34d399" />
            <div className="card-title">دليل الحلال</div>
          </div>
          <div className="card" onClick={() => setCurrentView('market_news')}>
            <span className="card-icon">📰</span>
            <div className="card-title">الأخبار</div>
          </div>
          <div className="card">
            <Activity size={24} color="#f472b6" />
            <div className="card-title">مصفوفة الارتباط</div>
          </div>
        </div>
      </section>


      <section className="chart-container">
        <div className="chart-header">
          <div>
            <div className="price">$84,580</div>
            <div className="price-sub">Bitcoin · 48h ₿</div>
          </div>
          <div className="trend-up">▲ 0.61%</div>
        </div>
        
        {/* Simple mock chart line */}
        <div style={{ height: '60px', width: '100%', borderBottom: '1px solid #1f2937', position: 'relative' }}>
           <svg viewBox="0 0 100 20" preserveAspectRatio="none" style={{ width: '100%', height: '100%', stroke: '#10b981', strokeWidth: 2, fill: 'none' }}>
              <path d="M0,15 Q10,10 20,12 T40,8 T60,10 T80,5 T100,2" />
           </svg>
        </div>

        <div className="chart-stats">
          <div className="stat-box">
            <div className="stat-title">أدنى 48h</div>
            <div className="stat-val">$83,861</div>
          </div>
          <div className="stat-box">
            <div className="stat-title">أعلى 48h</div>
            <div className="stat-val">$84,992</div>
          </div>
          <div className="stat-box">
            <div className="stat-title">الاتجاه</div>
            <div className="stat-val" style={{ color: '#10b981' }}>صاعد 📈</div>
          </div>
        </div>
      </section>

    </div>
  );
}

export default App;
